// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF265rxzqr3MVP8je1fUYg0TDh-YkZJ00',
    appId: '1:27633609133:web:fada887bb3d67f76375924',
    messagingSenderId: '27633609133',
    projectId: 'mycityapp-9155e',
    authDomain: 'mycityapp-9155e.firebaseapp.com',
    storageBucket: 'mycityapp-9155e.firebasestorage.app',
    measurementId: 'G-9LGSKL3126',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9F3YgcBA8BtS5u7_kFfX9gPqfiprqeQg',
    appId: '1:27633609133:android:0d27f1d8737afcb8375924',
    messagingSenderId: '27633609133',
    projectId: 'mycityapp-9155e',
    storageBucket: 'mycityapp-9155e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALG5QFfSnKuW5M3klJ7iDr9tNHLRlhWlE',
    appId: '1:27633609133:ios:76d45eaba4381f59375924',
    messagingSenderId: '27633609133',
    projectId: 'mycityapp-9155e',
    storageBucket: 'mycityapp-9155e.firebasestorage.app',
    iosClientId: '27633609133-mrkiaum7urgb96q108k7rfcrc2s3fqlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.assessment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALG5QFfSnKuW5M3klJ7iDr9tNHLRlhWlE',
    appId: '1:27633609133:ios:76d45eaba4381f59375924',
    messagingSenderId: '27633609133',
    projectId: 'mycityapp-9155e',
    storageBucket: 'mycityapp-9155e.firebasestorage.app',
    iosClientId: '27633609133-mrkiaum7urgb96q108k7rfcrc2s3fqlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.assessment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF265rxzqr3MVP8je1fUYg0TDh-YkZJ00',
    appId: '1:27633609133:web:12e322e9e5f80ab8375924',
    messagingSenderId: '27633609133',
    projectId: 'mycityapp-9155e',
    authDomain: 'mycityapp-9155e.firebaseapp.com',
    storageBucket: 'mycityapp-9155e.firebasestorage.app',
    measurementId: 'G-K3N71FW8QF',
  );

}